development:
  adapter: mysql
  database: todo_list_dev
  pool: 5
  timeout: 5000
  host: 127.0.0.1

test: &test
  adapter: mysql
  database: todo_list_test
  username: root
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: todo_list
  pool: 5
  timeout: 5000
  host: 127.0.0.1

cucumber:
  <<: *test